name: news_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_bloc: ^8.1.3 #state management
  equatable: ^2.0.5 #comparing dart objects
  get_it: ^7.6.0 #service locator
  intl: ^0.18.1 #dateFormat
  floor: ^1.4.2 #DataBase
  retrofit: ^4.0.1 #make request to api
  flutter_hooks: ^0.19.0 #Hooks
  cached_network_image: ^3.2.3 #cached Images
  dio: ^5.3.0
  ionicons: ^0.2.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator:
  floor_generator:
  build_runner:

flutter:
  uses-material-design: true